apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ecommerce
data:
  LOG_LEVEL: "info"
  DB_HOST: "postgres-0.postgres-headless.ecommerce.svc.cluster.local"
  DB_PORT: "5432"
